#ifndef COMMUNICATION_H
#define COMMUNICATION_H

enum class CAN_MESSAGE : unsigned long int {
  STEERING_WHEEL_BUTTONS = 0x290,
  CDC_HEARTBEAT = 0x3C8,
  CDC_HANDSHAKE_REQUEST = 0x6A1,
  CDC_HANDSHAKE_RESPONSE = 0x6A2,
};

#endif // COMMUNICATION_H
